# Generated by Django 6.0.3 on 2026-04-06 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'algorithmes',
            },
        ),
        migrations.CreateModel(
            name='Optimisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'optimisations',
            },
        ),
        migrations.CreateModel(
            name='Sommet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'db_table': 'sommets',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('algorithme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zones', to='administrator.algorithme')),
                ('optimisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='administrator.optimisation')),
            ],
            options={
                'db_table': 'zones',
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_totale', models.FloatField(default=0.0)),
                ('duree_totale', models.FloatField(default=0.0)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='administrator.zone')),
            ],
            options={
                'db_table': 'trajets',
            },
        ),
        migrations.CreateModel(
            name='TrajetSommet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('sommet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajet_sommets', to='administrator.sommet')),
                ('trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sommets', to='administrator.trajet')),
            ],
            options={
                'db_table': 'trajet_sommets',
                'ordering': ['ordre'],
                'unique_together': {('trajet', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='PointZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordre', models.PositiveIntegerField()),
                ('sommet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_zones', to='administrator.sommet')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='administrator.zone')),
            ],
            options={
                'db_table': 'point_zones',
                'ordering': ['ordre'],
                'unique_together': {('zone', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='accounts.user')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affectations', to='administrator.zone')),
            ],
            options={
                'db_table': 'affectations',
                'unique_together': {('user', 'zone')},
            },
        ),
    ]
