# Generated by Django 6.0.3 on 2026-04-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointzone',
            name='sommet',
        ),
        migrations.AddField(
            model_name='pointzone',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pointzone',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
