# Generated by Django 6.0.3 on 2026-04-09 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_remove_pointzone_sommet_pointzone_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trajetsommet',
            name='status',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('visite', 'Visité'), ('incident', 'Incident')], default='en_attente', max_length=20),
        ),
        migrations.AlterField(
            model_name='pointzone',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pointzone',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
